//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPlants.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlantsDatabaseEntities : DbContext
    {
        public PlantsDatabaseEntities()
            : base("name=PlantsDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<plantas> plantas { get; set; }
        public virtual DbSet<plantasUsuarios> plantasUsuarios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TformatoFolha> TformatoFolha { get; set; }
        public virtual DbSet<TpontaFolha> TpontaFolha { get; set; }
        public virtual DbSet<TtipoFlor> TtipoFlor { get; set; }
        public virtual DbSet<TtipoFruta> TtipoFruta { get; set; }
        public virtual DbSet<TtipoHaste> TtipoHaste { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
