//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPlants.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantasUsuarios
    {
        public Nullable<int> user_id { get; set; }
        public string plant_name { get; set; }
        public string description { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> formatoFolha { get; set; }
        public Nullable<int> pontaFolha { get; set; }
        public Nullable<int> tipoFlor { get; set; }
        public Nullable<int> tipoHaste { get; set; }
        public Nullable<int> tipoFruta { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public int id { get; set; }
    
        public virtual TformatoFolha TformatoFolha { get; set; }
        public virtual TpontaFolha TpontaFolha { get; set; }
        public virtual TtipoFlor TtipoFlor { get; set; }
        public virtual TtipoFruta TtipoFruta { get; set; }
        public virtual TtipoHaste TtipoHaste { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
